# Generated by Django 5.0 on 2023-12-20 20:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competency_matrix', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='discipline',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='disciplines', to=settings.AUTH_USER_MODEL),
        ),
    ]
