# Generated by Django 5.0 on 2023-12-18 19:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competency_matrix', '0002_track'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512)),
                ('slug', models.CharField(max_length=255, unique=True)),
                ('discipline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades_disciplines', to='competency_matrix.discipline')),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades_tracks', to='competency_matrix.track')),
                ('users', models.ManyToManyField(related_name='grades_users', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Грейд',
                'verbose_name_plural': 'Грейды',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512)),
                ('slug', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField()),
                ('discipline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='competency_matrix.discipline')),
            ],
            options={
                'verbose_name': 'Раздел',
                'verbose_name_plural': 'Разделы',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512)),
                ('slug', models.CharField(max_length=255, unique=True)),
                ('discipline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills_discipline', to='competency_matrix.discipline')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills_sections', to='competency_matrix.section')),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills_tracks', to='competency_matrix.track')),
            ],
            options={
                'verbose_name': 'Навык',
                'verbose_name_plural': 'Навык',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SkillDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills_grades', to='competency_matrix.grade')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills_descriptions', to='competency_matrix.skill')),
            ],
            options={
                'verbose_name': 'Описание навыка',
                'verbose_name_plural': 'Описания навыков',
                'ordering': ['description'],
            },
        ),
    ]
