# Generated by Django 5.0 on 2023-12-20 20:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('competency_matrix', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.CharField(max_length=255, unique=True)),
                ('discipline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracks', to='competency_matrix.discipline')),
                ('users', models.ManyToManyField(blank=True, related_name='tracks_users', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Трек развития',
                'verbose_name_plural': 'Треки развития',
                'ordering': ['name'],
            },
        ),
    ]
